// TYPES OF ACTIONS FOR PRODUCTS
export const FETCHING_PRODUCTS="FETCH_PRODUCTS_REQUEST";
export const FETCHING_PRODUCTS_LENGTH="FETCH_PRODUCTS_REQUEST_LENGTH";
export const FETCHING_SPESEFIC_PRODOCT="FETCH_PRODUCT_REQUEST";
export const FETCHING_CATEGORIES="FETCHING_CATEGORIES_REQUEST";
export const FETCHING_SUBCATEGORIES="FETCHING_SUBCATEGOIRES_REQUEST";
export const FETCHING_ORDERS="FETCH_ORDERS_REQUEST";
export const FETCHING_ORDER="FETCH_ORDER_REQUEST";
export const FETCHING_USERS="FETCH_USERS_REQUEST";
export const FETCHING_USER="FETCH_USER_REQUEST";
export const SHOW_INFO_MODAL="SHOW_INFO_MODAL";
export const SHOW_EDIT_MODAL="SHOW_EDIT_MODAL";
export const CALCULATE_NUMBER_OF_PRODUCT="CALCULATE_NUMBER_OF_PRODUCT"

