// TYPES OF ACTIONS FOR PRODUCTS
export const FETCHING_PRODUCTS="FETCH_PRODUCTS_REQUEST";
export const FETCHING_SPESEFIC_PRODOCT="FETCH_PRODUCT_REQUEST"
// export const FETCHING_PRODUCTS_SUCCESS="FETCH_PRODUCTS_SUCCESS"
// export const FETCHING_PRODUCTS_FAILURE="FETCH_PRODUCTS_FAILURE"
export const FETCHING_ORDERS="FETCH_ORDERS_REQUEST";
