// TYPES OF ACTIONS FOR PRODUCTS
export const FETCHING_PRODUCTS="FETCH_PRODUCTS_REQUEST";
export const FETCHING_SPESEFIC_PRODOCT="FETCH_PRODUCT_REQUEST"
export const FETCHING_ORDERS="FETCH_ORDERS_REQUEST";
export const FETCHING_ORDER="FETCH_ORDER_REQUEST";
export const FETCHING_USERS="FETCH_USERS_REQUEST";
export const FETCHING_USER="FETCH_USER_REQUEST";
