export const TableData={
    products:[
        {name:"موستانگ شلبی",country:"ایالات متحده", category:" کوپه", id:1 ,year:"2013",company:"شلبی فورد"},
        {name:" lx سمند",country:"ایران", category:"سدان خانوادگی", id:2 ,year:"2001",company:"ایران خودرو"},
        {name:"بی ام دابیو e46",country:"المان", category:"سدان کوپه", id:3 ,year:"2005",company:"بی ام دابلیو"},
        {name:"بنز s500",country:"المان", category:"سدان فول سایز", id:4 ,year:"2021",company:"بنز"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
        {name:"تویوتا GT86",country:"ژاپن", category:" کوپه", id:5 ,year:"2013",company:"تویوتا"},
    ],
}